### ISSUE TITLE
need help! can't build up the server~~

### ISSUE THREAD

**Issue by rcsama** [foxfriends/machi-koro#17]
ERROR in ./src/client/index.scss (./node_modules/css-loader!./node_modules/postcss-loader/lib!./node_modules/fast-sass-loader/lib!./src/client/index.scss)
    Module build failed (from ./node_modules/fast-sass-loader/lib/index.js):
    Error: Node Sass does not yet support your current environment: Linux Unsupported architecture (arm64) with Node.js 10.x
    For more information on which environments are supported please see:
    https://github.com/sass/node-sass/releases/tag/v7.0.0
        at module.exports (/home/parallels/machi-koro/node_modules/node-sass/lib/binding.js:13:13)
        at Object.<anonymous> (/home/parallels/machi-koro/node_modules/node-sass/lib/index.js:13:35)
        at Module._compile (/home/parallels/machi-koro/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
        at Module.load (internal/modules/cjs/loader.js:653:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
        at Function.Module._load (internal/modules/cjs/loader.js:585:3)
        at Module.require (internal/modules/cjs/loader.js:692:17)
        at require (/home/parallels/machi-koro/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
        at Object.<anonymous> (/home/parallels/machi-koro/node_modules/fast-sass-loader/lib/index.js:8:14)
        at Module._compile (/home/parallels/machi-koro/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
        at Module.load (internal/modules/cjs/loader.js:653:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
        at Function.Module._load (internal/modules/cjs/loader.js:585:3)
        at Module.require (internal/modules/cjs/loader.js:692:17)
        at require (/home/parallels/machi-koro/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
        at loadLoader (/home/parallels/machi-koro/node_modules/loader-runner/lib/loadLoader.js:18:17)
        at iteratePitchingLoaders (/home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
        at iteratePitchingLoaders (/home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
        at /home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:176:18
        at loadLoader (/home/parallels/machi-koro/node_modules/loader-runner/lib/loadLoader.js:47:3)
        at iteratePitchingLoaders (/home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
        at iteratePitchingLoaders (/home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
        at /home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:176:18
        at loadLoader (/home/parallels/machi-koro/node_modules/loader-runner/lib/loadLoader.js:47:3)
        at iteratePitchingLoaders (/home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
        at runLoaders (/home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:365:2)
        at NormalModule.doBuild (/home/parallels/machi-koro/node_modules/webpack/lib/NormalModule.js:295:3)
        at NormalModule.build (/home/parallels/machi-koro/node_modules/webpack/lib/NormalModule.js:446:15)
        at Compilation.buildModule (/home/parallels/machi-koro/node_modules/webpack/lib/Compilation.js:739:10)
        at factory.create (/home/parallels/machi-koro/node_modules/webpack/lib/Compilation.js:981:14)
        at factory (/home/parallels/machi-koro/node_modules/webpack/lib/NormalModuleFactory.js:409:6)
        at hooks.afterResolve.callAsync (/home/parallels/machi-koro/node_modules/webpack/lib/NormalModuleFactory.js:155:13)
        at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/home/parallels/machi-koro/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
        at resolver (/home/parallels/machi-koro/node_modules/webpack/lib/NormalModuleFactory.js:138:29)
     @ ./src/client/index.scss 4:14-174
     @ ./src/client/index.js
    
    ERROR in ./src/client/app/menu/index.scss (./node_modules/css-loader!./node_modules/postcss-loader/lib!./node_modules/fast-sass-loader/lib!./src/client/app/menu/index.scss)
    Module build failed (from ./node_modules/fast-sass-loader/lib/index.js):
    Error: Node Sass does not yet support your current environment: Linux Unsupported architecture (arm64) with Node.js 10.x
    For more information on which environments are supported please see:
    https://github.com/sass/node-sass/releases/tag/v7.0.0
        at module.exports (/home/parallels/machi-koro/node_modules/node-sass/lib/binding.js:13:13)
        at Object.<anonymous> (/home/parallels/machi-koro/node_modules/node-sass/lib/index.js:13:35)
        at Module._compile (/home/parallels/machi-koro/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
        at Module.load (internal/modules/cjs/loader.js:653:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
        at Function.Module._load (internal/modules/cjs/loader.js:585:3)
        at Module.require (internal/modules/cjs/loader.js:692:17)
        at require (/home/parallels/machi-koro/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
        at Object.<anonymous> (/home/parallels/machi-koro/node_modules/fast-sass-loader/lib/index.js:8:14)
        at Module._compile (/home/parallels/machi-koro/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
        at Module.load (internal/modules/cjs/loader.js:653:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
        at Function.Module._load (internal/modules/cjs/loader.js:585:3)
        at Module.require (internal/modules/cjs/loader.js:692:17)
        at require (/home/parallels/machi-koro/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
        at loadLoader (/home/parallels/machi-koro/node_modules/loader-runner/lib/loadLoader.js:18:17)
        at iteratePitchingLoaders (/home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
        at iteratePitchingLoaders (/home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
        at /home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:176:18
        at loadLoader (/home/parallels/machi-koro/node_modules/loader-runner/lib/loadLoader.js:47:3)
        at iteratePitchingLoaders (/home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
        at iteratePitchingLoaders (/home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
        at /home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:176:18
        at loadLoader (/home/parallels/machi-koro/node_modules/loader-runner/lib/loadLoader.js:47:3)
        at iteratePitchingLoaders (/home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
        at runLoaders (/home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:365:2)
        at NormalModule.doBuild (/home/parallels/machi-koro/node_modules/webpack/lib/NormalModule.js:295:3)
        at NormalModule.build (/home/parallels/machi-koro/node_modules/webpack/lib/NormalModule.js:446:15)
        at Compilation.buildModule (/home/parallels/machi-koro/node_modules/webpack/lib/Compilation.js:739:10)
        at factory.create (/home/parallels/machi-koro/node_modules/webpack/lib/Compilation.js:981:14)
        at factory (/home/parallels/machi-koro/node_modules/webpack/lib/NormalModuleFactory.js:409:6)
        at hooks.afterResolve.callAsync (/home/parallels/machi-koro/node_modules/webpack/lib/NormalModuleFactory.js:155:13)
        at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/home/parallels/machi-koro/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
        at resolver (/home/parallels/machi-koro/node_modules/webpack/lib/NormalModuleFactory.js:138:29)
     @ ./src/client/app/menu/index.scss 4:14-192
     @ ./src/client/app/menu/index.js
     @ ./src/client/app/index.js
     @ ./src/client/index.js
    
    ERROR in ./src/client/app/setup/index.scss (./node_modules/css-loader!./node_modules/postcss-loader/lib!./node_modules/fast-sass-loader/lib!./src/client/app/setup/index.scss)
    Module build failed (from ./node_modules/fast-sass-loader/lib/index.js):
    Error: Node Sass does not yet support your current environment: Linux Unsupported architecture (arm64) with Node.js 10.x
    For more information on which environments are supported please see:
    https://github.com/sass/node-sass/releases/tag/v7.0.0
        at module.exports (/home/parallels/machi-koro/node_modules/node-sass/lib/binding.js:13:13)
        at Object.<anonymous> (/home/parallels/machi-koro/node_modules/node-sass/lib/index.js:13:35)
        at Module._compile (/home/parallels/machi-koro/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
        at Module.load (internal/modules/cjs/loader.js:653:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
        at Function.Module._load (internal/modules/cjs/loader.js:585:3)
        at Module.require (internal/modules/cjs/loader.js:692:17)
        at require (/home/parallels/machi-koro/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
        at Object.<anonymous> (/home/parallels/machi-koro/node_modules/fast-sass-loader/lib/index.js:8:14)
        at Module._compile (/home/parallels/machi-koro/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
        at Module.load (internal/modules/cjs/loader.js:653:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
        at Function.Module._load (internal/modules/cjs/loader.js:585:3)
        at Module.require (internal/modules/cjs/loader.js:692:17)
        at require (/home/parallels/machi-koro/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
        at loadLoader (/home/parallels/machi-koro/node_modules/loader-runner/lib/loadLoader.js:18:17)
        at iteratePitchingLoaders (/home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
        at iteratePitchingLoaders (/home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
        at /home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:176:18
        at loadLoader (/home/parallels/machi-koro/node_modules/loader-runner/lib/loadLoader.js:47:3)
        at iteratePitchingLoaders (/home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
        at iteratePitchingLoaders (/home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
        at /home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:176:18
        at loadLoader (/home/parallels/machi-koro/node_modules/loader-runner/lib/loadLoader.js:47:3)
        at iteratePitchingLoaders (/home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
        at runLoaders (/home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:365:2)
        at NormalModule.doBuild (/home/parallels/machi-koro/node_modules/webpack/lib/NormalModule.js:295:3)
        at NormalModule.build (/home/parallels/machi-koro/node_modules/webpack/lib/NormalModule.js:446:15)
        at Compilation.buildModule (/home/parallels/machi-koro/node_modules/webpack/lib/Compilation.js:739:10)
        at factory.create (/home/parallels/machi-koro/node_modules/webpack/lib/Compilation.js:981:14)
        at factory (/home/parallels/machi-koro/node_modules/webpack/lib/NormalModuleFactory.js:409:6)
        at hooks.afterResolve.callAsync (/home/parallels/machi-koro/node_modules/webpack/lib/NormalModuleFactory.js:155:13)
        at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/home/parallels/machi-koro/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
        at resolver (/home/parallels/machi-koro/node_modules/webpack/lib/NormalModuleFactory.js:138:29)
     @ ./src/client/app/setup/index.scss 4:14-192
     @ ./src/client/app/setup/index.js
     @ ./src/client/app/index.js
     @ ./src/client/index.js
    
    ERROR in ./src/client/app/game/index.scss (./node_modules/css-loader!./node_modules/postcss-loader/lib!./node_modules/fast-sass-loader/lib!./src/client/app/game/index.scss)
    Module build failed (from ./node_modules/fast-sass-loader/lib/index.js):
    Error: Node Sass does not yet support your current environment: Linux Unsupported architecture (arm64) with Node.js 10.x
    For more information on which environments are supported please see:
    https://github.com/sass/node-sass/releases/tag/v7.0.0
        at module.exports (/home/parallels/machi-koro/node_modules/node-sass/lib/binding.js:13:13)
        at Object.<anonymous> (/home/parallels/machi-koro/node_modules/node-sass/lib/index.js:13:35)
        at Module._compile (/home/parallels/machi-koro/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
        at Module.load (internal/modules/cjs/loader.js:653:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
        at Function.Module._load (internal/modules/cjs/loader.js:585:3)
        at Module.require (internal/modules/cjs/loader.js:692:17)
        at require (/home/parallels/machi-koro/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
        at Object.<anonymous> (/home/parallels/machi-koro/node_modules/fast-sass-loader/lib/index.js:8:14)
        at Module._compile (/home/parallels/machi-koro/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
        at Module.load (internal/modules/cjs/loader.js:653:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
        at Function.Module._load (internal/modules/cjs/loader.js:585:3)
        at Module.require (internal/modules/cjs/loader.js:692:17)
        at require (/home/parallels/machi-koro/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
        at loadLoader (/home/parallels/machi-koro/node_modules/loader-runner/lib/loadLoader.js:18:17)
        at iteratePitchingLoaders (/home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
        at iteratePitchingLoaders (/home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
        at /home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:176:18
        at loadLoader (/home/parallels/machi-koro/node_modules/loader-runner/lib/loadLoader.js:47:3)
        at iteratePitchingLoaders (/home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
        at iteratePitchingLoaders (/home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
        at /home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:176:18
        at loadLoader (/home/parallels/machi-koro/node_modules/loader-runner/lib/loadLoader.js:47:3)
        at iteratePitchingLoaders (/home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
        at runLoaders (/home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:365:2)
        at NormalModule.doBuild (/home/parallels/machi-koro/node_modules/webpack/lib/NormalModule.js:295:3)
        at NormalModule.build (/home/parallels/machi-koro/node_modules/webpack/lib/NormalModule.js:446:15)
        at Compilation.buildModule (/home/parallels/machi-koro/node_modules/webpack/lib/Compilation.js:739:10)
        at factory.create (/home/parallels/machi-koro/node_modules/webpack/lib/Compilation.js:981:14)
        at factory (/home/parallels/machi-koro/node_modules/webpack/lib/NormalModuleFactory.js:409:6)
        at hooks.afterResolve.callAsync (/home/parallels/machi-koro/node_modules/webpack/lib/NormalModuleFactory.js:155:13)
        at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/home/parallels/machi-koro/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
        at resolver (/home/parallels/machi-koro/node_modules/webpack/lib/NormalModuleFactory.js:138:29)
     @ ./src/client/app/game/index.scss 4:14-192
     @ ./src/client/app/game/index.js
     @ ./src/client/app/index.js
     @ ./src/client/index.js
    
    ERROR in ./src/client/app/game/board.scss (./node_modules/css-loader!./node_modules/postcss-loader/lib!./node_modules/fast-sass-loader/lib!./src/client/app/game/board.scss)
    Module build failed (from ./node_modules/fast-sass-loader/lib/index.js):
    Error: Node Sass does not yet support your current environment: Linux Unsupported architecture (arm64) with Node.js 10.x
    For more information on which environments are supported please see:
    https://github.com/sass/node-sass/releases/tag/v7.0.0
        at module.exports (/home/parallels/machi-koro/node_modules/node-sass/lib/binding.js:13:13)
        at Object.<anonymous> (/home/parallels/machi-koro/node_modules/node-sass/lib/index.js:13:35)
        at Module._compile (/home/parallels/machi-koro/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
        at Module.load (internal/modules/cjs/loader.js:653:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
        at Function.Module._load (internal/modules/cjs/loader.js:585:3)
        at Module.require (internal/modules/cjs/loader.js:692:17)
        at require (/home/parallels/machi-koro/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
        at Object.<anonymous> (/home/parallels/machi-koro/node_modules/fast-sass-loader/lib/index.js:8:14)
        at Module._compile (/home/parallels/machi-koro/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
        at Module.load (internal/modules/cjs/loader.js:653:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
        at Function.Module._load (internal/modules/cjs/loader.js:585:3)
        at Module.require (internal/modules/cjs/loader.js:692:17)
        at require (/home/parallels/machi-koro/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
        at loadLoader (/home/parallels/machi-koro/node_modules/loader-runner/lib/loadLoader.js:18:17)
        at iteratePitchingLoaders (/home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
        at iteratePitchingLoaders (/home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
        at /home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:176:18
        at loadLoader (/home/parallels/machi-koro/node_modules/loader-runner/lib/loadLoader.js:47:3)
        at iteratePitchingLoaders (/home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
        at iteratePitchingLoaders (/home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
        at /home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:176:18
        at loadLoader (/home/parallels/machi-koro/node_modules/loader-runner/lib/loadLoader.js:47:3)
        at iteratePitchingLoaders (/home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
        at runLoaders (/home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:365:2)
        at NormalModule.doBuild (/home/parallels/machi-koro/node_modules/webpack/lib/NormalModule.js:295:3)
        at NormalModule.build (/home/parallels/machi-koro/node_modules/webpack/lib/NormalModule.js:446:15)
        at Compilation.buildModule (/home/parallels/machi-koro/node_modules/webpack/lib/Compilation.js:739:10)
        at factory.create (/home/parallels/machi-koro/node_modules/webpack/lib/Compilation.js:981:14)
        at factory (/home/parallels/machi-koro/node_modules/webpack/lib/NormalModuleFactory.js:409:6)
        at hooks.afterResolve.callAsync (/home/parallels/machi-koro/node_modules/webpack/lib/NormalModuleFactory.js:155:13)
        at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/home/parallels/machi-koro/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
        at resolver (/home/parallels/machi-koro/node_modules/webpack/lib/NormalModuleFactory.js:138:29)
     @ ./src/client/app/game/board.scss 4:14-192
     @ ./src/client/app/game/board.js
     @ ./src/client/app/game/index.js
     @ ./src/client/app/index.js
     @ ./src/client/index.js
    
    ERROR in ./src/client/app/game/player.scss (./node_modules/css-loader!./node_modules/postcss-loader/lib!./node_modules/fast-sass-loader/lib!./src/client/app/game/player.scss)
    Module build failed (from ./node_modules/fast-sass-loader/lib/index.js):
    Error: Node Sass does not yet support your current environment: Linux Unsupported architecture (arm64) with Node.js 10.x
    For more information on which environments are supported please see:
    https://github.com/sass/node-sass/releases/tag/v7.0.0
        at module.exports (/home/parallels/machi-koro/node_modules/node-sass/lib/binding.js:13:13)
        at Object.<anonymous> (/home/parallels/machi-koro/node_modules/node-sass/lib/index.js:13:35)
        at Module._compile (/home/parallels/machi-koro/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
        at Module.load (internal/modules/cjs/loader.js:653:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
        at Function.Module._load (internal/modules/cjs/loader.js:585:3)
        at Module.require (internal/modules/cjs/loader.js:692:17)
        at require (/home/parallels/machi-koro/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
        at Object.<anonymous> (/home/parallels/machi-koro/node_modules/fast-sass-loader/lib/index.js:8:14)
        at Module._compile (/home/parallels/machi-koro/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
        at Module.load (internal/modules/cjs/loader.js:653:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
        at Function.Module._load (internal/modules/cjs/loader.js:585:3)
        at Module.require (internal/modules/cjs/loader.js:692:17)
        at require (/home/parallels/machi-koro/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
        at loadLoader (/home/parallels/machi-koro/node_modules/loader-runner/lib/loadLoader.js:18:17)
        at iteratePitchingLoaders (/home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
        at iteratePitchingLoaders (/home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
        at /home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:176:18
        at loadLoader (/home/parallels/machi-koro/node_modules/loader-runner/lib/loadLoader.js:47:3)
        at iteratePitchingLoaders (/home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
        at iteratePitchingLoaders (/home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
        at /home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:176:18
        at loadLoader (/home/parallels/machi-koro/node_modules/loader-runner/lib/loadLoader.js:47:3)
        at iteratePitchingLoaders (/home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
        at runLoaders (/home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:365:2)
        at NormalModule.doBuild (/home/parallels/machi-koro/node_modules/webpack/lib/NormalModule.js:295:3)
        at NormalModule.build (/home/parallels/machi-koro/node_modules/webpack/lib/NormalModule.js:446:15)
        at Compilation.buildModule (/home/parallels/machi-koro/node_modules/webpack/lib/Compilation.js:739:10)
        at factory.create (/home/parallels/machi-koro/node_modules/webpack/lib/Compilation.js:981:14)
        at factory (/home/parallels/machi-koro/node_modules/webpack/lib/NormalModuleFactory.js:409:6)
        at hooks.afterResolve.callAsync (/home/parallels/machi-koro/node_modules/webpack/lib/NormalModuleFactory.js:155:13)
        at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/home/parallels/machi-koro/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
        at resolver (/home/parallels/machi-koro/node_modules/webpack/lib/NormalModuleFactory.js:138:29)
     @ ./src/client/app/game/player.scss 4:14-193
     @ ./src/client/app/game/player.js
     @ ./src/client/app/game/index.js
     @ ./src/client/app/index.js
     @ ./src/client/index.js
    
    ERROR in ./src/client/app/game/controls.scss (./node_modules/css-loader!./node_modules/postcss-loader/lib!./node_modules/fast-sass-loader/lib!./src/client/app/game/controls.scss)
    Module build failed (from ./node_modules/fast-sass-loader/lib/index.js):
    Error: Node Sass does not yet support your current environment: Linux Unsupported architecture (arm64) with Node.js 10.x
    For more information on which environments are supported please see:
    https://github.com/sass/node-sass/releases/tag/v7.0.0
        at module.exports (/home/parallels/machi-koro/node_modules/node-sass/lib/binding.js:13:13)
        at Object.<anonymous> (/home/parallels/machi-koro/node_modules/node-sass/lib/index.js:13:35)
        at Module._compile (/home/parallels/machi-koro/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
        at Module.load (internal/modules/cjs/loader.js:653:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
        at Function.Module._load (internal/modules/cjs/loader.js:585:3)
        at Module.require (internal/modules/cjs/loader.js:692:17)
        at require (/home/parallels/machi-koro/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
        at Object.<anonymous> (/home/parallels/machi-koro/node_modules/fast-sass-loader/lib/index.js:8:14)
        at Module._compile (/home/parallels/machi-koro/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
        at Module.load (internal/modules/cjs/loader.js:653:32)
        at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
        at Function.Module._load (internal/modules/cjs/loader.js:585:3)
        at Module.require (internal/modules/cjs/loader.js:692:17)
        at require (/home/parallels/machi-koro/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
        at loadLoader (/home/parallels/machi-koro/node_modules/loader-runner/lib/loadLoader.js:18:17)
        at iteratePitchingLoaders (/home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
        at iteratePitchingLoaders (/home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
        at /home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:176:18
        at loadLoader (/home/parallels/machi-koro/node_modules/loader-runner/lib/loadLoader.js:47:3)
        at iteratePitchingLoaders (/home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
        at iteratePitchingLoaders (/home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
        at /home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:176:18
        at loadLoader (/home/parallels/machi-koro/node_modules/loader-runner/lib/loadLoader.js:47:3)
        at iteratePitchingLoaders (/home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
        at runLoaders (/home/parallels/machi-koro/node_modules/loader-runner/lib/LoaderRunner.js:365:2)
        at NormalModule.doBuild (/home/parallels/machi-koro/node_modules/webpack/lib/NormalModule.js:295:3)
        at NormalModule.build (/home/parallels/machi-koro/node_modules/webpack/lib/NormalModule.js:446:15)
        at Compilation.buildModule (/home/parallels/machi-koro/node_modules/webpack/lib/Compilation.js:739:10)
        at factory.create (/home/parallels/machi-koro/node_modules/webpack/lib/Compilation.js:981:14)
        at factory (/home/parallels/machi-koro/node_modules/webpack/lib/NormalModuleFactory.js:409:6)
        at hooks.afterResolve.callAsync (/home/parallels/machi-koro/node_modules/webpack/lib/NormalModuleFactory.js:155:13)
        at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/home/parallels/machi-koro/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
        at resolver (/home/parallels/machi-koro/node_modules/webpack/lib/NormalModuleFactory.js:138:29)
     @ ./src/client/app/game/controls.scss 4:14-195
     @ ./src/client/app/game/controls.js
     @ ./src/client/app/game/index.js
     @ ./src/client/app/index.js
     @ ./src/client/index.js
Child
    Hash: fb9519eedfd012bd47a6
    Time: 1135ms
    Built at: 02/21/2022 11:13:18 AM
        Asset      Size  Chunks             Chunk Names
    server.js  79.4 KiB    main  [emitted]  main
    Entrypoint main = server.js
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {main} [built]
    [./src/cards.js] 6.63 KiB {main} [built]
    [./src/landmarks.js] 1.05 KiB {main} [built]
    [./src/server/index.js] 6 KiB {main} [built]
    [./src/server/store/game.js] 7.62 KiB {main} [built]
    [./src/server/store/index.js] 478 bytes {main} [built]
    [./src/server/store/setup.js] 2.95 KiB {main} [built]
    [express] external "require('express')" 42 bytes {main} [built]
    [socket.io] external "require('socket.io')" 42 bytes {main} [built]
        + 20 hidden modules
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! machi-koro@1.0.0 build: `NODE_ENV=production webpack`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the machi-koro@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/parallels/.npm/_logs/2022-02-21T03_13_18_502Z-debug.log

**Comment by rcsama** [comment]
I'm figure out the solution: My cpu is M1 based arm64 and I just manually install some of the plugins which elder version was not support arm64 and it can run! great game! I have fun with my colleagues! Though this version of the game is outdated we may add some DLC in the future, right?

**Comment by foxfriends** [comment]
Ah glad you figured it out! 

I am not currently planning on adding any expansions to this, but if you want to you can try to add them yourself.
